version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: mysql://root@localhost/circle_test?sslmode=disable
      - image: circleci/mysql:5.7 # an example of how to specify a service container
    environment:
          #MYSQL_ROOT_PASSWORD:
          #MYSQL_DATABASE: mysql
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
    
    working directory: ~/django-circleci-deployment
    
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: sudo pip install pip --upgrade
      - run: sudo apt-get update
      - run: sudo pip install configparser
      - run: sudo pip install mysql-connector-python
      - run: sudo apt-get install libmysqlclient-dev
      #- run: sudo pip install mysql-python
      - run: sudo apt-get install python-mysqldb
      - run: sudo pip install mysqlclient
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps25-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python -m pip install django
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Start database server
          command: |
            sudo service mysql start
            sleep 2
            ps aux | grep mysql
      - run:
          name: Create non-admin user
          command: |
            sudo mysql -u root -e "CREATE user myuser IDENTIFIED BY 'password';"

      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          key: deps25-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            #pipenv run python manage.py test
            . venv/bin/activate
            python manage.py runserver
            
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
